### ISSUE TITLE
ScaleManager.setScreenSize Deprecated

### ISSUE THREAD

**Issue by cdubz** [appsbu-de/phaserJumpstart#1]
[setScreenSize was deprecated in Phaser 2.4](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md#deprecated) and apparently replaced by [updateLayout()](https://github.com/photonstorm/phaser/blob/486c15f16fd7c2f154d55cb0239fa0dbdeaed1f8/src/core/ScaleManager.js#L1313).

Currently, loading this project on mobile throws an error because setScreenSize is used at [Line 29 of Boot.js](https://github.com/appsbu-de/phaserJumpstart/blob/master/states/Boot.js#L29).

I'm not quite clear on what this accomplishes for the boot, so I didn't do a PR.

**Comment by casarock** [comment]
I'll take a deeper look. thanks for reporting!

**Comment by casarock** [comment]
Ropen. isn'T fixed ;)
