### ISSUE TITLE
Remove debug and unused code

### ISSUE THREAD

**Issue by cdubz** [appsbu-de/phaserJumpstart#2]
Apparently I can't PR anyway (:

There is some [commented-out debugging code in Game.render()](https://github.com/appsbu-de/phaserJumpstart/blob/master/states/Game.js#L18) and an unused [Game.renderGroup(member)](https://github.com/appsbu-de/phaserJumpstart/blob/master/states/Game.js#L27) function.

Providing some boilerplate debug functions may not be a bad idea though.

**Comment by casarock** [comment]
Thats right. I'll remove it. Thanks for reporting!

**Comment by cdubz** [comment]
I have also since learned how to do a PR, hah.
